# Verwenden eines vorhandenen Docker-Images als Basis
FROM nginx:alpine

# Kopieren der HTML-Datei ins Arbeitsverzeichnis des NGINX-Servers
COPY index.html /usr/share/nginx/html/index.html

# Exponieren des Ports 80, auf dem der NGINX-Server läuft
EXPOSE 80
